//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetrixGroupPlugins.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PatternIndex {
            get {
                return ((int)(this["PatternIndex"]));
            }
            set {
                this["PatternIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0001")]
        public double Tolerance {
            get {
                return ((double)(this["Tolerance"]));
            }
            set {
                this["Tolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableMultiClusterToolLayer {
            get {
                return ((bool)(this["EnableMultiClusterToolLayer"]));
            }
            set {
                this["EnableMultiClusterToolLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DesignIndex {
            get {
                return ((int)(this["DesignIndex"]));
            }
            set {
                this["DesignIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PERFORATION")]
        public string PerforationLayerName {
            get {
                return ((string)(this["PerforationLayerName"]));
            }
            set {
                this["PerforationLayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CLUSTER TOOL")]
        public string ClusterLayerName {
            get {
                return ((string)(this["ClusterLayerName"]));
            }
            set {
                this["ClusterLayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DrawClusterOnSeparateLayer {
            get {
                return ((bool)(this["DrawClusterOnSeparateLayer"]));
            }
            set {
                this["DrawClusterOnSeparateLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int AtomicMaxSearch {
            get {
                return ((int)(this["AtomicMaxSearch"]));
            }
            set {
                this["AtomicMaxSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int PoissonIterations {
            get {
                return ((int)(this["PoissonIterations"]));
            }
            set {
                this["PoissonIterations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAtomicProgress {
            get {
                return ((bool)(this["ShowAtomicProgress"]));
            }
            set {
                this["ShowAtomicProgress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DETAILS VIEW")]
        public string DetailViewLayerName {
            get {
                return ((string)(this["DetailViewLayerName"]));
            }
            set {
                this["DetailViewLayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TOOL HIT")]
        public string ToolHitLayerName {
            get {
                return ((string)(this["ToolHitLayerName"]));
            }
            set {
                this["ToolHitLayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CTSPinX {
            get {
                return ((int)(this["CTSPinX"]));
            }
            set {
                this["CTSPinX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int CTSPinY {
            get {
                return ((int)(this["CTSPinY"]));
            }
            set {
                this["CTSPinY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CTSXMulti {
            get {
                return ((int)(this["CTSXMulti"]));
            }
            set {
                this["CTSXMulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CTSYMulti {
            get {
                return ((int)(this["CTSYMulti"]));
            }
            set {
                this["CTSYMulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CTSAllowOP {
            get {
                return ((bool)(this["CTSAllowOP"]));
            }
            set {
                this["CTSAllowOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DesignFileLocation {
            get {
                return ((string)(this["DesignFileLocation"]));
            }
            set {
                this["DesignFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double PanelBorderDefault {
            get {
                return ((double)(this["PanelBorderDefault"]));
            }
            set {
                this["PanelBorderDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CLUSTER SAMPLE")]
        public string ClusterSampleLayerName {
            get {
                return ((string)(this["ClusterSampleLayerName"]));
            }
            set {
                this["ClusterSampleLayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double FixingHoleSize {
            get {
                return ((double)(this["FixingHoleSize"]));
            }
            set {
                this["FixingHoleSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double FixingHoleOffsetX {
            get {
                return ((double)(this["FixingHoleOffsetX"]));
            }
            set {
                this["FixingHoleOffsetX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double FixingHoleOffsetY {
            get {
                return ((double)(this["FixingHoleOffsetY"]));
            }
            set {
                this["FixingHoleOffsetY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public double FixingHoleSpacing {
            get {
                return ((double)(this["FixingHoleSpacing"]));
            }
            set {
                this["FixingHoleSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double FixingHoleMinimum {
            get {
                return ((double)(this["FixingHoleMinimum"]));
            }
            set {
                this["FixingHoleMinimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ClusterToolRotation {
            get {
                return ((double)(this["ClusterToolRotation"]));
            }
            set {
                this["ClusterToolRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DOTS")]
        public string DotFontLayerName {
            get {
                return ((string)(this["DotFontLayerName"]));
            }
            set {
                this["DotFontLayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.5")]
        public double DotMatrixHeight {
            get {
                return ((double)(this["DotMatrixHeight"]));
            }
            set {
                this["DotMatrixHeight"] = value;
            }
        }
    }
}
